/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * license agreements; and to You under the Apache License, version 2.0:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * This file is part of the Apache Pekko project, which was derived from Akka.
 */

/*
 * Copyright (C) 2019-2022 Lightbend Inc. <https://www.lightbend.com>
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TwoPhaseSetMessages.proto

// Protobuf Java Version: 3.25.6
package docs.ddata.protobuf.msg;

public final class TwoPhaseSetMessages {
  private TwoPhaseSetMessages() {}
  public static void registerAllExtensions(
      org.apache.pekko.protobufv3.internal.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      org.apache.pekko.protobufv3.internal.ExtensionRegistry registry) {
    registerAllExtensions(
        (org.apache.pekko.protobufv3.internal.ExtensionRegistryLite) registry);
  }
  public interface TwoPhaseSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:docs.ddata.TwoPhaseSet)
      org.apache.pekko.protobufv3.internal.MessageOrBuilder {

    /**
     * <code>repeated string adds = 1;</code>
     * @return A list containing the adds.
     */
    java.util.List<java.lang.String>
        getAddsList();
    /**
     * <code>repeated string adds = 1;</code>
     * @return The count of adds.
     */
    int getAddsCount();
    /**
     * <code>repeated string adds = 1;</code>
     * @param index The index of the element to return.
     * @return The adds at the given index.
     */
    java.lang.String getAdds(int index);
    /**
     * <code>repeated string adds = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the adds at the given index.
     */
    org.apache.pekko.protobufv3.internal.ByteString
        getAddsBytes(int index);

    /**
     * <code>repeated string removals = 2;</code>
     * @return A list containing the removals.
     */
    java.util.List<java.lang.String>
        getRemovalsList();
    /**
     * <code>repeated string removals = 2;</code>
     * @return The count of removals.
     */
    int getRemovalsCount();
    /**
     * <code>repeated string removals = 2;</code>
     * @param index The index of the element to return.
     * @return The removals at the given index.
     */
    java.lang.String getRemovals(int index);
    /**
     * <code>repeated string removals = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the removals at the given index.
     */
    org.apache.pekko.protobufv3.internal.ByteString
        getRemovalsBytes(int index);
  }
  /**
   * Protobuf type {@code docs.ddata.TwoPhaseSet}
   */
  public static final class TwoPhaseSet extends
      org.apache.pekko.protobufv3.internal.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:docs.ddata.TwoPhaseSet)
      TwoPhaseSetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TwoPhaseSet.newBuilder() to construct.
    private TwoPhaseSet(org.apache.pekko.protobufv3.internal.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TwoPhaseSet() {
      adds_ =
          org.apache.pekko.protobufv3.internal.LazyStringArrayList.emptyList();
      removals_ =
          org.apache.pekko.protobufv3.internal.LazyStringArrayList.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        org.apache.pekko.protobufv3.internal.GeneratedMessageV3.UnusedPrivateParameter unused) {
      return new TwoPhaseSet();
    }

    public static final org.apache.pekko.protobufv3.internal.Descriptors.Descriptor
        getDescriptor() {
      return docs.ddata.protobuf.msg.TwoPhaseSetMessages.internal_static_docs_ddata_TwoPhaseSet_descriptor;
    }

    @java.lang.Override
    protected org.apache.pekko.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return docs.ddata.protobuf.msg.TwoPhaseSetMessages.internal_static_docs_ddata_TwoPhaseSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet.class, docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet.Builder.class);
    }

    public static final int ADDS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private org.apache.pekko.protobufv3.internal.LazyStringArrayList adds_ =
        org.apache.pekko.protobufv3.internal.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string adds = 1;</code>
     * @return A list containing the adds.
     */
    public org.apache.pekko.protobufv3.internal.ProtocolStringList
        getAddsList() {
      return adds_;
    }
    /**
     * <code>repeated string adds = 1;</code>
     * @return The count of adds.
     */
    public int getAddsCount() {
      return adds_.size();
    }
    /**
     * <code>repeated string adds = 1;</code>
     * @param index The index of the element to return.
     * @return The adds at the given index.
     */
    public java.lang.String getAdds(int index) {
      return adds_.get(index);
    }
    /**
     * <code>repeated string adds = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the adds at the given index.
     */
    public org.apache.pekko.protobufv3.internal.ByteString
        getAddsBytes(int index) {
      return adds_.getByteString(index);
    }

    public static final int REMOVALS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private org.apache.pekko.protobufv3.internal.LazyStringArrayList removals_ =
        org.apache.pekko.protobufv3.internal.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string removals = 2;</code>
     * @return A list containing the removals.
     */
    public org.apache.pekko.protobufv3.internal.ProtocolStringList
        getRemovalsList() {
      return removals_;
    }
    /**
     * <code>repeated string removals = 2;</code>
     * @return The count of removals.
     */
    public int getRemovalsCount() {
      return removals_.size();
    }
    /**
     * <code>repeated string removals = 2;</code>
     * @param index The index of the element to return.
     * @return The removals at the given index.
     */
    public java.lang.String getRemovals(int index) {
      return removals_.get(index);
    }
    /**
     * <code>repeated string removals = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the removals at the given index.
     */
    public org.apache.pekko.protobufv3.internal.ByteString
        getRemovalsBytes(int index) {
      return removals_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(org.apache.pekko.protobufv3.internal.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < adds_.size(); i++) {
        org.apache.pekko.protobufv3.internal.GeneratedMessageV3.writeString(output, 1, adds_.getRaw(i));
      }
      for (int i = 0; i < removals_.size(); i++) {
        org.apache.pekko.protobufv3.internal.GeneratedMessageV3.writeString(output, 2, removals_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < adds_.size(); i++) {
          dataSize += computeStringSizeNoTag(adds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAddsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < removals_.size(); i++) {
          dataSize += computeStringSizeNoTag(removals_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRemovalsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet)) {
        return super.equals(obj);
      }
      docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet other = (docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet) obj;

      if (!getAddsList()
          .equals(other.getAddsList())) return false;
      if (!getRemovalsList()
          .equals(other.getRemovalsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAddsCount() > 0) {
        hash = (37 * hash) + ADDS_FIELD_NUMBER;
        hash = (53 * hash) + getAddsList().hashCode();
      }
      if (getRemovalsCount() > 0) {
        hash = (37 * hash) + REMOVALS_FIELD_NUMBER;
        hash = (53 * hash) + getRemovalsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet parseFrom(
        java.nio.ByteBuffer data)
        throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet parseFrom(
        java.nio.ByteBuffer data,
        org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet parseFrom(
        org.apache.pekko.protobufv3.internal.ByteString data)
        throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet parseFrom(
        org.apache.pekko.protobufv3.internal.ByteString data,
        org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet parseFrom(byte[] data)
        throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet parseFrom(
        byte[] data,
        org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return org.apache.pekko.protobufv3.internal.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet parseFrom(
        java.io.InputStream input,
        org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return org.apache.pekko.protobufv3.internal.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return org.apache.pekko.protobufv3.internal.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet parseDelimitedFrom(
        java.io.InputStream input,
        org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return org.apache.pekko.protobufv3.internal.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet parseFrom(
        org.apache.pekko.protobufv3.internal.CodedInputStream input)
        throws java.io.IOException {
      return org.apache.pekko.protobufv3.internal.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet parseFrom(
        org.apache.pekko.protobufv3.internal.CodedInputStream input,
        org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return org.apache.pekko.protobufv3.internal.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        org.apache.pekko.protobufv3.internal.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code docs.ddata.TwoPhaseSet}
     */
    public static final class Builder extends
        org.apache.pekko.protobufv3.internal.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:docs.ddata.TwoPhaseSet)
        docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSetOrBuilder {
      public static final org.apache.pekko.protobufv3.internal.Descriptors.Descriptor
          getDescriptor() {
        return docs.ddata.protobuf.msg.TwoPhaseSetMessages.internal_static_docs_ddata_TwoPhaseSet_descriptor;
      }

      @java.lang.Override
      protected org.apache.pekko.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return docs.ddata.protobuf.msg.TwoPhaseSetMessages.internal_static_docs_ddata_TwoPhaseSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet.class, docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet.Builder.class);
      }

      // Construct using docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet.newBuilder()
      private Builder() {

      }

      private Builder(
          org.apache.pekko.protobufv3.internal.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        adds_ =
            org.apache.pekko.protobufv3.internal.LazyStringArrayList.emptyList();
        removals_ =
            org.apache.pekko.protobufv3.internal.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public org.apache.pekko.protobufv3.internal.Descriptors.Descriptor
          getDescriptorForType() {
        return docs.ddata.protobuf.msg.TwoPhaseSetMessages.internal_static_docs_ddata_TwoPhaseSet_descriptor;
      }

      @java.lang.Override
      public docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet getDefaultInstanceForType() {
        return docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet.getDefaultInstance();
      }

      @java.lang.Override
      public docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet build() {
        docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet buildPartial() {
        docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet result = new docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          adds_.makeImmutable();
          result.adds_ = adds_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          removals_.makeImmutable();
          result.removals_ = removals_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          org.apache.pekko.protobufv3.internal.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          org.apache.pekko.protobufv3.internal.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          org.apache.pekko.protobufv3.internal.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          org.apache.pekko.protobufv3.internal.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          org.apache.pekko.protobufv3.internal.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(org.apache.pekko.protobufv3.internal.Message other) {
        if (other instanceof docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet) {
          return mergeFrom((docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet other) {
        if (other == docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet.getDefaultInstance()) return this;
        if (!other.adds_.isEmpty()) {
          if (adds_.isEmpty()) {
            adds_ = other.adds_;
            bitField0_ |= 0x00000001;
          } else {
            ensureAddsIsMutable();
            adds_.addAll(other.adds_);
          }
          onChanged();
        }
        if (!other.removals_.isEmpty()) {
          if (removals_.isEmpty()) {
            removals_ = other.removals_;
            bitField0_ |= 0x00000002;
          } else {
            ensureRemovalsIsMutable();
            removals_.addAll(other.removals_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          org.apache.pekko.protobufv3.internal.CodedInputStream input,
          org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.apache.pekko.protobufv3.internal.ByteString bs = input.readBytes();
                ensureAddsIsMutable();
                adds_.add(bs);
                break;
              } // case 10
              case 18: {
                org.apache.pekko.protobufv3.internal.ByteString bs = input.readBytes();
                ensureRemovalsIsMutable();
                removals_.add(bs);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private org.apache.pekko.protobufv3.internal.LazyStringArrayList adds_ =
          org.apache.pekko.protobufv3.internal.LazyStringArrayList.emptyList();
      private void ensureAddsIsMutable() {
        if (!adds_.isModifiable()) {
          adds_ = new org.apache.pekko.protobufv3.internal.LazyStringArrayList(adds_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated string adds = 1;</code>
       * @return A list containing the adds.
       */
      public org.apache.pekko.protobufv3.internal.ProtocolStringList
          getAddsList() {
        adds_.makeImmutable();
        return adds_;
      }
      /**
       * <code>repeated string adds = 1;</code>
       * @return The count of adds.
       */
      public int getAddsCount() {
        return adds_.size();
      }
      /**
       * <code>repeated string adds = 1;</code>
       * @param index The index of the element to return.
       * @return The adds at the given index.
       */
      public java.lang.String getAdds(int index) {
        return adds_.get(index);
      }
      /**
       * <code>repeated string adds = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the adds at the given index.
       */
      public org.apache.pekko.protobufv3.internal.ByteString
          getAddsBytes(int index) {
        return adds_.getByteString(index);
      }
      /**
       * <code>repeated string adds = 1;</code>
       * @param index The index to set the value at.
       * @param value The adds to set.
       * @return This builder for chaining.
       */
      public Builder setAdds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureAddsIsMutable();
        adds_.set(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string adds = 1;</code>
       * @param value The adds to add.
       * @return This builder for chaining.
       */
      public Builder addAdds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureAddsIsMutable();
        adds_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string adds = 1;</code>
       * @param values The adds to add.
       * @return This builder for chaining.
       */
      public Builder addAllAdds(
          java.lang.Iterable<java.lang.String> values) {
        ensureAddsIsMutable();
        org.apache.pekko.protobufv3.internal.AbstractMessageLite.Builder.addAll(
            values, adds_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string adds = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAdds() {
        adds_ =
          org.apache.pekko.protobufv3.internal.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string adds = 1;</code>
       * @param value The bytes of the adds to add.
       * @return This builder for chaining.
       */
      public Builder addAddsBytes(
          org.apache.pekko.protobufv3.internal.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureAddsIsMutable();
        adds_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private org.apache.pekko.protobufv3.internal.LazyStringArrayList removals_ =
          org.apache.pekko.protobufv3.internal.LazyStringArrayList.emptyList();
      private void ensureRemovalsIsMutable() {
        if (!removals_.isModifiable()) {
          removals_ = new org.apache.pekko.protobufv3.internal.LazyStringArrayList(removals_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated string removals = 2;</code>
       * @return A list containing the removals.
       */
      public org.apache.pekko.protobufv3.internal.ProtocolStringList
          getRemovalsList() {
        removals_.makeImmutable();
        return removals_;
      }
      /**
       * <code>repeated string removals = 2;</code>
       * @return The count of removals.
       */
      public int getRemovalsCount() {
        return removals_.size();
      }
      /**
       * <code>repeated string removals = 2;</code>
       * @param index The index of the element to return.
       * @return The removals at the given index.
       */
      public java.lang.String getRemovals(int index) {
        return removals_.get(index);
      }
      /**
       * <code>repeated string removals = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the removals at the given index.
       */
      public org.apache.pekko.protobufv3.internal.ByteString
          getRemovalsBytes(int index) {
        return removals_.getByteString(index);
      }
      /**
       * <code>repeated string removals = 2;</code>
       * @param index The index to set the value at.
       * @param value The removals to set.
       * @return This builder for chaining.
       */
      public Builder setRemovals(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureRemovalsIsMutable();
        removals_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string removals = 2;</code>
       * @param value The removals to add.
       * @return This builder for chaining.
       */
      public Builder addRemovals(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureRemovalsIsMutable();
        removals_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string removals = 2;</code>
       * @param values The removals to add.
       * @return This builder for chaining.
       */
      public Builder addAllRemovals(
          java.lang.Iterable<java.lang.String> values) {
        ensureRemovalsIsMutable();
        org.apache.pekko.protobufv3.internal.AbstractMessageLite.Builder.addAll(
            values, removals_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string removals = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemovals() {
        removals_ =
          org.apache.pekko.protobufv3.internal.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string removals = 2;</code>
       * @param value The bytes of the removals to add.
       * @return This builder for chaining.
       */
      public Builder addRemovalsBytes(
          org.apache.pekko.protobufv3.internal.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureRemovalsIsMutable();
        removals_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final org.apache.pekko.protobufv3.internal.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final org.apache.pekko.protobufv3.internal.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:docs.ddata.TwoPhaseSet)
    }

    // @@protoc_insertion_point(class_scope:docs.ddata.TwoPhaseSet)
    private static final docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet();
    }

    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final org.apache.pekko.protobufv3.internal.Parser<TwoPhaseSet>
        PARSER = new org.apache.pekko.protobufv3.internal.AbstractParser<TwoPhaseSet>() {
      @java.lang.Override
      public TwoPhaseSet parsePartialFrom(
          org.apache.pekko.protobufv3.internal.CodedInputStream input,
          org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
          throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (org.apache.pekko.protobufv3.internal.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static org.apache.pekko.protobufv3.internal.Parser<TwoPhaseSet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public org.apache.pekko.protobufv3.internal.Parser<TwoPhaseSet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TwoPhaseSet2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:docs.ddata.TwoPhaseSet2)
      org.apache.pekko.protobufv3.internal.MessageOrBuilder {

    /**
     * <code>optional bytes adds = 1;</code>
     * @return Whether the adds field is set.
     */
    boolean hasAdds();
    /**
     * <code>optional bytes adds = 1;</code>
     * @return The adds.
     */
    org.apache.pekko.protobufv3.internal.ByteString getAdds();

    /**
     * <code>optional bytes removals = 2;</code>
     * @return Whether the removals field is set.
     */
    boolean hasRemovals();
    /**
     * <code>optional bytes removals = 2;</code>
     * @return The removals.
     */
    org.apache.pekko.protobufv3.internal.ByteString getRemovals();
  }
  /**
   * <pre>
   *#twophaseset2
   * </pre>
   *
   * Protobuf type {@code docs.ddata.TwoPhaseSet2}
   */
  public static final class TwoPhaseSet2 extends
      org.apache.pekko.protobufv3.internal.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:docs.ddata.TwoPhaseSet2)
      TwoPhaseSet2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TwoPhaseSet2.newBuilder() to construct.
    private TwoPhaseSet2(org.apache.pekko.protobufv3.internal.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TwoPhaseSet2() {
      adds_ = org.apache.pekko.protobufv3.internal.ByteString.EMPTY;
      removals_ = org.apache.pekko.protobufv3.internal.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        org.apache.pekko.protobufv3.internal.GeneratedMessageV3.UnusedPrivateParameter unused) {
      return new TwoPhaseSet2();
    }

    public static final org.apache.pekko.protobufv3.internal.Descriptors.Descriptor
        getDescriptor() {
      return docs.ddata.protobuf.msg.TwoPhaseSetMessages.internal_static_docs_ddata_TwoPhaseSet2_descriptor;
    }

    @java.lang.Override
    protected org.apache.pekko.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return docs.ddata.protobuf.msg.TwoPhaseSetMessages.internal_static_docs_ddata_TwoPhaseSet2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2.class, docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2.Builder.class);
    }

    private int bitField0_;
    public static final int ADDS_FIELD_NUMBER = 1;
    private org.apache.pekko.protobufv3.internal.ByteString adds_ = org.apache.pekko.protobufv3.internal.ByteString.EMPTY;
    /**
     * <code>optional bytes adds = 1;</code>
     * @return Whether the adds field is set.
     */
    @java.lang.Override
    public boolean hasAdds() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes adds = 1;</code>
     * @return The adds.
     */
    @java.lang.Override
    public org.apache.pekko.protobufv3.internal.ByteString getAdds() {
      return adds_;
    }

    public static final int REMOVALS_FIELD_NUMBER = 2;
    private org.apache.pekko.protobufv3.internal.ByteString removals_ = org.apache.pekko.protobufv3.internal.ByteString.EMPTY;
    /**
     * <code>optional bytes removals = 2;</code>
     * @return Whether the removals field is set.
     */
    @java.lang.Override
    public boolean hasRemovals() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes removals = 2;</code>
     * @return The removals.
     */
    @java.lang.Override
    public org.apache.pekko.protobufv3.internal.ByteString getRemovals() {
      return removals_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(org.apache.pekko.protobufv3.internal.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, adds_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, removals_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += org.apache.pekko.protobufv3.internal.CodedOutputStream
          .computeBytesSize(1, adds_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += org.apache.pekko.protobufv3.internal.CodedOutputStream
          .computeBytesSize(2, removals_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2)) {
        return super.equals(obj);
      }
      docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 other = (docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2) obj;

      if (hasAdds() != other.hasAdds()) return false;
      if (hasAdds()) {
        if (!getAdds()
            .equals(other.getAdds())) return false;
      }
      if (hasRemovals() != other.hasRemovals()) return false;
      if (hasRemovals()) {
        if (!getRemovals()
            .equals(other.getRemovals())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAdds()) {
        hash = (37 * hash) + ADDS_FIELD_NUMBER;
        hash = (53 * hash) + getAdds().hashCode();
      }
      if (hasRemovals()) {
        hash = (37 * hash) + REMOVALS_FIELD_NUMBER;
        hash = (53 * hash) + getRemovals().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 parseFrom(
        java.nio.ByteBuffer data)
        throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 parseFrom(
        java.nio.ByteBuffer data,
        org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 parseFrom(
        org.apache.pekko.protobufv3.internal.ByteString data)
        throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 parseFrom(
        org.apache.pekko.protobufv3.internal.ByteString data,
        org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 parseFrom(byte[] data)
        throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 parseFrom(
        byte[] data,
        org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return org.apache.pekko.protobufv3.internal.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 parseFrom(
        java.io.InputStream input,
        org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return org.apache.pekko.protobufv3.internal.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return org.apache.pekko.protobufv3.internal.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 parseDelimitedFrom(
        java.io.InputStream input,
        org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return org.apache.pekko.protobufv3.internal.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 parseFrom(
        org.apache.pekko.protobufv3.internal.CodedInputStream input)
        throws java.io.IOException {
      return org.apache.pekko.protobufv3.internal.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 parseFrom(
        org.apache.pekko.protobufv3.internal.CodedInputStream input,
        org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return org.apache.pekko.protobufv3.internal.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        org.apache.pekko.protobufv3.internal.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *#twophaseset2
     * </pre>
     *
     * Protobuf type {@code docs.ddata.TwoPhaseSet2}
     */
    public static final class Builder extends
        org.apache.pekko.protobufv3.internal.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:docs.ddata.TwoPhaseSet2)
        docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2OrBuilder {
      public static final org.apache.pekko.protobufv3.internal.Descriptors.Descriptor
          getDescriptor() {
        return docs.ddata.protobuf.msg.TwoPhaseSetMessages.internal_static_docs_ddata_TwoPhaseSet2_descriptor;
      }

      @java.lang.Override
      protected org.apache.pekko.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return docs.ddata.protobuf.msg.TwoPhaseSetMessages.internal_static_docs_ddata_TwoPhaseSet2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2.class, docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2.Builder.class);
      }

      // Construct using docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2.newBuilder()
      private Builder() {

      }

      private Builder(
          org.apache.pekko.protobufv3.internal.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        adds_ = org.apache.pekko.protobufv3.internal.ByteString.EMPTY;
        removals_ = org.apache.pekko.protobufv3.internal.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public org.apache.pekko.protobufv3.internal.Descriptors.Descriptor
          getDescriptorForType() {
        return docs.ddata.protobuf.msg.TwoPhaseSetMessages.internal_static_docs_ddata_TwoPhaseSet2_descriptor;
      }

      @java.lang.Override
      public docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 getDefaultInstanceForType() {
        return docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2.getDefaultInstance();
      }

      @java.lang.Override
      public docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 build() {
        docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 buildPartial() {
        docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 result = new docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.adds_ = adds_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.removals_ = removals_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          org.apache.pekko.protobufv3.internal.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          org.apache.pekko.protobufv3.internal.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          org.apache.pekko.protobufv3.internal.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          org.apache.pekko.protobufv3.internal.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          org.apache.pekko.protobufv3.internal.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(org.apache.pekko.protobufv3.internal.Message other) {
        if (other instanceof docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2) {
          return mergeFrom((docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 other) {
        if (other == docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2.getDefaultInstance()) return this;
        if (other.hasAdds()) {
          setAdds(other.getAdds());
        }
        if (other.hasRemovals()) {
          setRemovals(other.getRemovals());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          org.apache.pekko.protobufv3.internal.CodedInputStream input,
          org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                adds_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                removals_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private org.apache.pekko.protobufv3.internal.ByteString adds_ = org.apache.pekko.protobufv3.internal.ByteString.EMPTY;
      /**
       * <code>optional bytes adds = 1;</code>
       * @return Whether the adds field is set.
       */
      @java.lang.Override
      public boolean hasAdds() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes adds = 1;</code>
       * @return The adds.
       */
      @java.lang.Override
      public org.apache.pekko.protobufv3.internal.ByteString getAdds() {
        return adds_;
      }
      /**
       * <code>optional bytes adds = 1;</code>
       * @param value The adds to set.
       * @return This builder for chaining.
       */
      public Builder setAdds(org.apache.pekko.protobufv3.internal.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        adds_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes adds = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAdds() {
        bitField0_ = (bitField0_ & ~0x00000001);
        adds_ = getDefaultInstance().getAdds();
        onChanged();
        return this;
      }

      private org.apache.pekko.protobufv3.internal.ByteString removals_ = org.apache.pekko.protobufv3.internal.ByteString.EMPTY;
      /**
       * <code>optional bytes removals = 2;</code>
       * @return Whether the removals field is set.
       */
      @java.lang.Override
      public boolean hasRemovals() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes removals = 2;</code>
       * @return The removals.
       */
      @java.lang.Override
      public org.apache.pekko.protobufv3.internal.ByteString getRemovals() {
        return removals_;
      }
      /**
       * <code>optional bytes removals = 2;</code>
       * @param value The removals to set.
       * @return This builder for chaining.
       */
      public Builder setRemovals(org.apache.pekko.protobufv3.internal.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        removals_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes removals = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemovals() {
        bitField0_ = (bitField0_ & ~0x00000002);
        removals_ = getDefaultInstance().getRemovals();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final org.apache.pekko.protobufv3.internal.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final org.apache.pekko.protobufv3.internal.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:docs.ddata.TwoPhaseSet2)
    }

    // @@protoc_insertion_point(class_scope:docs.ddata.TwoPhaseSet2)
    private static final docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2();
    }

    public static docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final org.apache.pekko.protobufv3.internal.Parser<TwoPhaseSet2>
        PARSER = new org.apache.pekko.protobufv3.internal.AbstractParser<TwoPhaseSet2>() {
      @java.lang.Override
      public TwoPhaseSet2 parsePartialFrom(
          org.apache.pekko.protobufv3.internal.CodedInputStream input,
          org.apache.pekko.protobufv3.internal.ExtensionRegistryLite extensionRegistry)
          throws org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (org.apache.pekko.protobufv3.internal.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new org.apache.pekko.protobufv3.internal.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static org.apache.pekko.protobufv3.internal.Parser<TwoPhaseSet2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public org.apache.pekko.protobufv3.internal.Parser<TwoPhaseSet2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public docs.ddata.protobuf.msg.TwoPhaseSetMessages.TwoPhaseSet2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final org.apache.pekko.protobufv3.internal.Descriptors.Descriptor
    internal_static_docs_ddata_TwoPhaseSet_descriptor;
  private static final 
    org.apache.pekko.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable
      internal_static_docs_ddata_TwoPhaseSet_fieldAccessorTable;
  private static final org.apache.pekko.protobufv3.internal.Descriptors.Descriptor
    internal_static_docs_ddata_TwoPhaseSet2_descriptor;
  private static final 
    org.apache.pekko.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable
      internal_static_docs_ddata_TwoPhaseSet2_fieldAccessorTable;

  public static org.apache.pekko.protobufv3.internal.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  org.apache.pekko.protobufv3.internal.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031TwoPhaseSetMessages.proto\022\ndocs.ddata\"" +
      "-\n\013TwoPhaseSet\022\014\n\004adds\030\001 \003(\t\022\020\n\010removals" +
      "\030\002 \003(\t\".\n\014TwoPhaseSet2\022\014\n\004adds\030\001 \001(\014\022\020\n\010" +
      "removals\030\002 \001(\014B\033\n\027docs.ddata.protobuf.ms" +
      "gH\001"
    };
    descriptor = org.apache.pekko.protobufv3.internal.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new org.apache.pekko.protobufv3.internal.Descriptors.FileDescriptor[] {
        });
    internal_static_docs_ddata_TwoPhaseSet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_docs_ddata_TwoPhaseSet_fieldAccessorTable = new
      org.apache.pekko.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable(
        internal_static_docs_ddata_TwoPhaseSet_descriptor,
        new java.lang.String[] { "Adds", "Removals", });
    internal_static_docs_ddata_TwoPhaseSet2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_docs_ddata_TwoPhaseSet2_fieldAccessorTable = new
      org.apache.pekko.protobufv3.internal.GeneratedMessageV3.FieldAccessorTable(
        internal_static_docs_ddata_TwoPhaseSet2_descriptor,
        new java.lang.String[] { "Adds", "Removals", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
