# https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

github:
  description: "Build highly concurrent, distributed, and resilient message-driven applications using Java/Scala"
  homepage: https://pekko.apache.org/
  labels:
    - pekko
    - streaming
    - reactive
    - actor-model
    - concurrency
    - cloud-native
    - distributed-actors
    - distributed-systems
    - high-performance
    - message-driven

  protected_tags:
    - "v*.*.*"

  dependabot_alerts:  true
  dependabot_updates: false

  features:
    # Enable wiki for documentation
    wiki: true
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: true
    # Enable github discussions
    discussions: true

  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  true

  protected_branches:
    main:
      required_status_checks:
        # strict means "Require branches to be up to date before merging".
        strict: false
        # contexts are the names of checks that must pass
        contexts:
          - Code is formatted
          - Check headers
      required_pull_request_reviews:
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        required_approving_review_count: 1
    1.0.x:
      required_status_checks:
        # strict means "Require branches to be up to date before merging".
        strict: false
        # contexts are the names of checks that must pass
        contexts:
          - Code is formatted
          - Check headers
      required_pull_request_reviews:
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        required_approving_review_count: 1
    1.1.x:
      required_status_checks:
        # strict means "Require branches to be up to date before merging".
        strict: false
        # contexts are the names of checks that must pass
        contexts:
          - Code is formatted
          - Check headers
      required_pull_request_reviews:
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        required_approving_review_count: 1
    1.2.x:
      required_status_checks:
        # strict means "Require branches to be up to date before merging".
        strict: false
        # contexts are the names of checks that must pass
        contexts:
          - Code is formatted
          - Check headers
      required_pull_request_reviews:
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        required_approving_review_count: 1
    1.3.x:
      required_status_checks:
        # strict means "Require branches to be up to date before merging".
        strict: false
        # contexts are the names of checks that must pass
        contexts:
          - Code is formatted
          - Check headers
      required_pull_request_reviews:
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        required_approving_review_count: 1

notifications:
  commits:              commits@pekko.apache.org
  issues:               notifications@pekko.apache.org
  pullrequests:         notifications@pekko.apache.org
  discussions:          notifications@pekko.apache.org
  jobs:                 notifications@pekko.apache.org
