// .scalafix.conf
rules = [
  RemoveUnused
  OrganizeImports
  ExplicitResultTypes
  fix.scala213.DottyMigrate
//  fix.scala213.NullaryOverride
]
//NullaryOverride.mode = Rewrite
ExplicitResultTypes {
  memberVisibility = [] # only rewrite implicit members
  skipSimpleDefinitions = []
}
ExplicitImplicitTypes.symbolReplacements {
  "scala/concurrent/ExecutionContextExecutor#" = "scala/concurrent/ExecutionContext#"
}
RemoveUnused.imports = false
RemoveUnused.privates = false
RemoveUnused.locals = false

//ignored files
ignored-files = [
  "TypedBenchmarkActors.scala",
  "FlowPrependSpec.scala",
  "FlowZipSpec.scala",
  "FlowZipWithSpec.scala",
  "FlowZipWithIndexSpec.scala",
  "SourceSpec.scala",
  "StatsSampleSpec.scala",
  "ActorFlowSpec.scala",
  "FSMTimingSpec.scala",
  "ThreadPoolVirtualThreadSpec.scala",
  "ForkJoinPoolVirtualThreadSpec.scala",
  "VirtualThreadPoolDispatcherSpec.scala"
]

//ignored packages
ignored-packages = [
  "docs",
  "doc",
  "jdoc"
]

OrganizeImports {
  blankLines = Auto
  coalesceToWildcardImportThreshold = null
  expandRelative = false
  groupedImports = Keep
  groups = [
    "re:javax?\\.",
    "scala.",
    "com.sun.",
    "re:org\\.apache\\.pekko",
    "pekko.",
    "org.reactivestreams.",
    "io.netty.",
    "org.scalatest.",
    "org.slf4j.",
    "com.typesafe.",
    "*"
  ]
  importSelectorsOrder = Ascii
  importsOrder = Ascii
  removeUnused = true
  targetDialect = StandardLayout
}
