#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

export PW=`cat password`

# A CA rotation that keeps the distinguished name produces a second CA certificate sharing the
# subject of ./genca.sh's exampleCA but holding a different key pair. Only the original one
# signed the certificates generated by ./gencerts.sh.
keytool -genkeypair -v \
  -alias exampleca-rotated \
  -dname "CN=exampleCA, OU=Example Org, O=Example Company, L=San Francisco, ST=California, C=US" \
  -keystore exampleca-rotated.p12 \
  -storetype PKCS12 \
  -keypass:env PW \
  -storepass:env PW \
  -keyalg EC \
  -keysize 256 \
  -ext KeyUsage:critical="keyCertSign" \
  -ext BasicConstraints:critical="ca:true" \
  -validity 9999

keytool -export -v \
  -alias exampleca-rotated \
  -file exampleca-rotated.crt \
  -keypass:env PW \
  -storepass:env PW \
  -keystore exampleca-rotated.p12 \
  -storetype PKCS12 \
  -rfc

# keytool writes CRLF on some platforms, the other certificates here use LF
tr -d '\r' < exampleca-rotated.crt > exampleca-rotated.crt.tmp
mv exampleca-rotated.crt.tmp exampleca-rotated.crt

# the rotated CA never signs anything, so its private key is not kept around
rm exampleca-rotated.p12

# A `ca-cert-file` bundling two unrelated CA certificates.
cat exampleca.crt pem/selfsigned-certificate.pem > exampleca-bundle.crt

# A `ca-cert-file` bundling two CA certificates with the same subject, as seen mid-rotation.
# The one that signed the node certificates comes first, so picking the last match is wrong.
cat exampleca.crt exampleca-rotated.crt > exampleca-rotated-bundle.crt
